# font_family      CaskaydiaCove Nerd Font Mono
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
enable_audio_bell no
font_size 11.0
window_padding_width 25
include theme.conf
#background_opacity 0.60
#hide_window_decorations yes
#confirm_os_window_close 0


# BEGIN_KITTY_FONTS
# font_family      family="JetBrainsMono Nerd Font"
font_family      family="IosevkaTerm Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6AA,U+F000-U+F2FF,U+F300-U+F381,U+F500-U+FD46 IosevkaTerm Nerd Font Mono

# END_KITTY_FONTS
